# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Video": "VideoBlock.ipynb",
         "RisizeTime": "VideoBlock.ipynb",
         "encodes": "VideoBlock.ipynb"}

modules = ["VideoBlock.py"]

doc_url = "https://ThesisSlayer.github.io/modules_th/"

git_url = "https://github.com/ThesisSlayer/modules_th/tree/master/"

def custom_doc_links(name): return None
