# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"AdaptiveConcatPool3d": "02_inflator.ipynb",
         "get_hps": "02_inflator.ipynb",
         "inflate": "02_inflator.ipynb",
         "show_frames": "03_video_block.ipynb",
         "Video": "03_video_block.ipynb",
         "ResizeTime": "03_video_block.ipynb",
         "encodes": "03_video_block.ipynb",
         "uniformize_dataset": "03_video_block.ipynb",
         "UniformLabelsCallback": "03_video_block.ipynb",
         "snippets_from_video": "03_video_block.ipynb",
         "DF2Paths": "Untitled.ipynb"}

modules = ["inflator.py",
           "video_block.py",
           "data_set.py"]

doc_url = "https://ThesisSlayer.github.io/modules_th/"

git_url = "https://github.com/ThesisSlayer/modules_th/tree/master/"

def custom_doc_links(name): return None
