# AUTOGENERATED! DO NOT EDIT! File to edit: Untitled.ipynb (unless otherwise specified).

__all__ = ['DF2Paths']

# Cell
from fastai.vision.all import *
from .video_block import *
from pathlib import Path
import pandas as pd

class DF2Paths(Transform):
    def __init__(self, path, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.path = path

    def encodes(self, df:pd.Series):
        Id, start, end = df['id'], df['start'], df['end']
        def fr(t): return int(float(t)*24)
        start, end = fr(start) + 1, fr(end)
        step = -1 if start > end else 1                     # If start is greater than end,
                                                            # it reverses the order of the for loop
                                                            # This because it seems some videos are in reverse
        vid = [str(self.path/'Charades_v1_rgb'/Id/f'{Id}-{n:0>6d}.jpg') for n in range(start, end, step)]
        return vid