# AUTOGENERATED! DO NOT EDIT! File to edit: 12_load_r2p1d_model.ipynb (unless otherwise specified).

__all__ = ['r2p1d_model_K', 'r2p1d_model_KM', 'inserted_models']

# Cell
import torch
import torch.nn as nn
from fastai.vision.all import *

from resnetmodels.models.resnet2p1d import generate_model
from resnetmodels.model import load_pretrained_model

# Cell
def r2p1d_model_K(pretrained=False,progress=True):
    r2p1d = generate_model(50,n_classes=700)
    if pretrained:
        return load_pretrained_model(r2p1d, '/mnt/data/eugeniomarinelli/pretrained/r2p1d50_K_200ep.pth','r2p1d50_K_200ep.pth', n_finetune_classes=101 )
    return r2p1d

# Cell
def r2p1d_model_KM(pretrained=False,progress=True):
    r2p1d = generate_model(50,n_classes=1039)
    if pretrained:
        return load_pretrained_model(r2p1d, '/mnt/data/eugeniomarinelli/pretrained/r2p1d50_KM_200ep.pth','r2p1d50_KM_200ep.pth', n_finetune_classes=101 )
    return r2p1d

# Cell
inserted_models = {'r2p1d50_KM': r2p1d_model_KM,
                   'r2p1d50_K': r2p1d_model_K,
                   'res50_2d': resnet50}